baseURL = "/"
title = "Stories4You"
author = "Mr. Teller"
ignoreErrors = ["error-remote-getjson"]

[Params]
  [Params.Terminal]
  # Note: color schema
  # Note: You can choose between
  # Note: ["monokai", "powershell", "gruvbox_light", "gruvbox_dark", "solarized_light", "solarized_dark", "ubuntu", "retro"]
  schema = "monokai"

  # Note: in terminal
  # [userName]@[pcName]:~/$ cd [workDir]
  # [userName]@[pcName]:~/[workDir]$ cat [profile]
  #
  # [description]
  #
  # Note: if you set Params.Tree > user = true
  # [userName]@[pcName]:~/[workDir]$ tree ./[folderName]/
  # ./[folderName]/
  # ...
  # Note: result of the tree command
  userName = "Mr. Teller"
  pcName = "stories4you"
  workDir = "stories"
  profile = "profile.txt"

  # Note: speed at which text is displayed on the terminal
  terminalDelay = 20

  # Note: speed at which text is displayed on the activity pages
  activityDelay = 5
  
  description = """
  Hey there this is Mr. Teller I will be telling you stories related to real world also some fantacy stories.

  """
  [Params.Tree]
  use = true
  folderName = "stories_list"
  # Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
  files = [ 
    
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
